# ~/~ begin <<README.md#./docker-stack.yml>>[init]
services:
  # ~/~ begin <<README.md#services>>[init]
  pihole:
    image: pihole/pihole:latest
    ports:
      - target: 53
        published: 53
        mode: host
        protocol: tcp
      - target: 53
        published: 53
        mode: host
        protocol: udp
      - target: 443
        published: 443
        mode: host
        protocol: tcp
      - target: 80
        published: 80
        mode: host
        protocol: tcp
    environment:
      TZ: "America/Los_Angeles"
      WEBPASSWORD_FILE: /run/secrets/pihole_web_admin_pass
      FTLCONF_dns_listenMode: "ALL"
    volumes:
      - /srv/pihole:/etc/pihole
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == pihole
  # ~/~ end
  # ~/~ begin <<README.md#services>>[1]
  copyparty:
    image: copyparty/ac:latest
    ports:
      - target: 3923
        published: 3923
        mode: host
        protocol: tcp
    command: ["-p", "3923", "-e2dsa", "-e2ts", "--usernames", "--ah-alg", "argon2"]
    volumes:
      - /srv/copyparty/copyparty.conf:/cfg/config.conf:ro
      - /srv/copyparty/db:/cfg/hists
      - /srv/copyparty/media:/media
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == copyparty
  # ~/~ end
  # ~/~ begin <<README.md#services>>[2]
  forgejo:
    image: codeberg.org/forgejo/forgejo:15
    ports:
      - target: 3000
        published: 3000
        mode: host
        protocol: tcp
      - target: 22
        published: 22
        mode: host
        protocol: tcp
    environment:
      USER_PID: 1000
      USER_GID: 1000
    volumes:
      - /srv/forgejo:/data
      - /etc/localtime:/etc/localtime:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == forgejo
  # ~/~ end
  # ~/~ begin <<README.md#services>>[3]
  syncthing:
    image: syncthing/syncthing:latest
    ports: 
      - target: 8384
        published: 8384
        mode: host
        protocol: tcp
    environment:
      USER_PID: 1000
      USER_GID: 1000
    volumes:
      - /srv/syncthing/data:/data
      - /srv/syncthing/synced:/synced
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.hostname == syncthing
  # ~/~ end

secrets:
  # ~/~ begin <<README.md#secrets>>[init]
  pihole_web_admin_pass:
    external: true
  # ~/~ end
# ~/~ end
